
test:
  feedback_email_to:      [shirin.faenza@ucop.edu]
  feedback_email_from:    no-reply-dash@ucop.edu
  root_url:               http://dash-dev


local:
  feedback_email_to:      [shirin.faenza@ucop.edu, perry.willett@ucop.edu, mstrong@ucop.edu]
  feedback_email_from:    no-reply-dash@ucop.edu
  root_url:               http://dash-dev


development:
  feedback_email_to:      [shirin.faenza@ucop.edu, perry.willett@ucop.edu, mstrong@ucop.edu]
  feedback_email_from:    no-reply-dash@ucop.edu
  root_url:               http://dash-dev


stage:
  feedback_email_to:      [uc3@ucop.edu]
  feedback_email_from:    no-reply-dash@ucop.edu
  root_url:               http://dash-stg          


production:
  feedback_email_to:      [uc3@ucop.edu]
  feedback_email_from:    no-reply-dash@ucop.edu
  root_url:               http://dash





campus_emails:
  cdl:        uc3@ucop.edu
  uci:        mjmckinl@uci.edu
  ucla:       data@library.ucla.edu
  ucsd:       unknown@unknown.com
  ucsb:       unknown@unknown.com
  ucb:        webman@library.berkeley.edu
  ucd:        unknown@unknown.com
  ucm:        curation@ucmerced.edu
  ucr:        unknown@unknown.com
  ucsf:       unknown@unknown.com
  ucsc:       unknown@unknown.com
  unknown:    unknown@unknown.com