development:
  # feedback_email_to:      [pwillet.ucop.edu, mstrong@ucop.edu, sfisher@ucop.edu]
  feedback_email_to:      [shirin.faenza@ucop.edu, pwillet.ucop.edu, mstrong@ucop.edu]
  feedback_email_from:    no-reply-dash@ucop.edu

development_nonlocal:
  development

local:
  development

test_nonlocal:
  development

test:
  feedback_email_to:      [shirin.faenza@ucop.edu]
  feedback_email_from:    no-reply-dash@ucop.edu

production:
  feedback_email_to:      [uc3@ucop.edu]
  feedback_email_from:    no-reply-dash@ucop.edu


campus_emails:
  cdl:        unknown@unknown.com
  uci:        unknown@unknown.com
  ucla:       unknown@unknown.com
  ucsd:       unknown@unknown.com
  ucsb:       unknown@unknown.com
  ucb:        webman@library.berkeley.edu
  ucd:        unknown@unknown.com
  ucm:        unknown@unknown.com
  ucr:        unknown@unknown.com
  ucsf:       unknown@unknown.com
  ucsc:       unknown@unknown.com
  unknown:    unknown@unknown.com