

test:
  feedback_email_to:      [shirin.faenza@ucop.edu]
  feedback_email_from:    no-reply-dash@ucop.edu
  root_url:               http://dash-dev


local:
  feedback_email_to:      [shirin.faenza@ucop.edu, perry.willett@ucop.edu, mstrong@ucop.edu]
  feedback_email_from:    no-reply-dash@ucop.edu
  root_url:               http://dash-dev
  client_id:              395059284700-3bt120tssk8vau4sfm9cb9d4ctifab32.apps.googleusercontent.com
  client_secret:          USZ3KqtmuqwWUL90AgT7F439


development:
  feedback_email_to:      [shirin.faenza@ucop.edu, perry.willett@ucop.edu, mstrong@ucop.edu]
  feedback_email_from:    no-reply-dash@ucop.edu
  root_url:               http://dash-dev2
  client_id:              395059284700-3bt120tssk8vau4sfm9cb9d4ctifab32.apps.googleusercontent.com
  client_secret:          USZ3KqtmuqwWUL90AgT7F439

stage:
  feedback_email_to:      [uc3@ucop.edu]
  feedback_email_from:    no-reply-dash@ucop.edu
  root_url:               http://dash-stg
  client_id:              18187250368-7eddsv9k8bn4mhh8kdo7t8g75uhuooo9.apps.googleusercontent.com
  client_secret:          z3RAasfO-7jsNYRm6Fd3W5su
  google_analytics_key:   UA-30638119-13

production:
  feedback_email_to:      [uc3@ucop.edu]
  feedback_email_from:    no-reply-dash@ucop.edu
  root_url:               http://dash
  client_id:              68997685259-putqitkba0a0a9so0a6gvcaprr5ek0sj.apps.googleusercontent.com
  client_secret:          T90gJ-gAIXfiyYoKcoG7zSOF



campus_emails:
  cdl:        uc3@ucop.edu
  uci:        mjmckinl@uci.edu
  ucla:       data@library.ucla.edu
  ucsd:       unknown@unknown.com
  ucsb:       unknown@unknown.com
  ucb:        data-consult@lists.berkeley.edu
  ucd:        unknown@unknown.com
  ucm:        curation@ucmerced.edu
  ucr:        unknown@unknown.com
  ucsf:       unknown@unknown.com
  ucsc:       scer@library.ucsc.edu
  dataone:    uc3@ucop.edu
  lbnl:       help@lbl.gov
  unknown:    unknown@unknown.com



