defaults: &DEFAULTS
    uploads_dir: uploads
    datashare_url: "http://localhost:8080"
    external_identifier: "eppn"
    logout_path: "/logout_page"
       
development:
    <<: *DEFAULTS
    
test:
    uploads_dir: test_uploads
    datashare_url: "http://hostname.ucsf.edu"
    external_identifier: "eppn"
    logout_path: "/logout_page"

production:
    uploads_dir: uploads
    datashare_url: "http://hostname.ucsf.edu"
    external_identifier: "eppn"
    logout_path: "/Shibboleth.sso/Logout"