defaults: &DEFAULTS
    uploads_dir: uploads
    datashare_url: "http://localhost:8080"
    external_identifier: "eppn"
    user_email_from_shibboleth: "mail"
    first_name_from_shibboleth: "givenName"
    last_name_from_shibboleth: "sn"
    logout_path: "/logout_page"
       
local:
    uploads_dir: uploads
    external_identifier: "eppn"
    user_email_from_shibboleth: "mail"
    first_name_from_shibboleth: "givenName"
    last_name_from_shibboleth: "sn"
    logout_path: "/logout_page"

development:
    uploads_dir: uploads
    external_identifier: "eppn"
    user_email_from_shibboleth: "mail"
    first_name_from_shibboleth: "givenName"
    last_name_from_shibboleth: "sn"
    logout_path: "/logout_page"

stage:
    uploads_dir: uploads
    external_identifier: "eppn"
    user_email_from_shibboleth: "mail"
    first_name_from_shibboleth: "givenName"
    last_name_from_shibboleth: "sn"
    logout_path: "/logout_page"    

    
test:
    uploads_dir: test_uploads
    external_identifier: "eppn"
    user_email_from_shibboleth: "mail"
    first_name_from_shibboleth: "givenName"
    last_name_from_shibboleth: "sn"
    logout_path: "/logout_page"

production:
    uploads_dir: uploads
    external_identifier: "eppn"
    user_email_from_shibboleth: "mail"
    first_name_from_shibboleth: "givenName"
    last_name_from_shibboleth: "sn"
    logout_path: "/logout_page"
