defaults: &DEFAULTS
    uploads_dir: uploads
    datashare_url: "http://localhost:8080"
    external_identifier: "eppn"
    logout_path: "/logout_page"
       
development:
    uploads_dir: uploads
    datashare_cdl_url: "http://dash-dev.cdlib.org"
    datashare_ucb_url: "http://dash-dev.berkeley.edu"
    datashare_ucla_url: "http://dev.dash.ucla.edu"
    external_identifier: "eppn"
    logout_path: "/logout_page"

    
test:
    uploads_dir: test_uploads
    datashare_url: "http://hostname.ucsf.edu"
    external_identifier: "eppn"
    logout_path: "/logout_page"

production:
    uploads_dir: uploads
    datashare_url: "http://hostname.ucsf.edu"
    external_identifier: "eppn"
    logout_path: "/Shibboleth.sso/Logout"
